# Generated by Django 5.2.5 on 2025-09-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
