# Generated by Django 5.2.5 on 2025-10-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
